### ISSUE TITLE
Not every Heasoft version is compatible with OSA

### ISSUE THREAD

**Issue by ferrigno** [ISDC-integral/osa-python-docker#2]
As stated in [OSA doc](https://www.isdc.unige.ch/integral/download/osa/doc/11.2/osa_inst_guide/node1.html)
heasoft above 6.28 is not fully compatible with OSA.

The README should be updated accordingly

**Comment by volodymyrss** [comment]
this container is not only needed for OSA.

**Comment by ferrigno** [comment]
Current version of heasoft is 6.32.1, but what's the point of installing OSA with incompatible verison of heasoft?

**Comment by volodymyrss** [comment]
the point is that not all OSA does not work. In fact, only certain set of scripts does not. All of the tools, and ddosa, work.

**Comment by volodymyrss** [comment]
By the way 6.28 is [not what's built here](https://github.com/ISDC-integral/osa-python-docker/blob/c565686afd65b59bdccdffbb86ef26ccae9e74e3/Makefile#L6) by default.

Let's try to be a bit more careful and descriptive.

You can build any version you want with this, there is nothing to downgrade in the repo.

**Comment by ferrigno** [comment]
6.28 is what is [written in the Dockefile](https://github.com/ISDC-integral/osa-python-docker/blob/c565686afd65b59bdccdffbb86ef26ccae9e74e3/Dockerfile#L83) I have not seen the Makefile. Fine with me if this is what is needed.

**Comment by volodymyrss** [comment]
I think it is a good point that this peculiarity should be added in a README.md
